server:
  port: 10000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: aliyun_esc:8848
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aliyun_esc:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: SaraIsRoot

mybatis-plus:
  # mapper映射文件路径
  mapper-locations: classpath:/mapper/product/*.xml
  global-config:
    db-config:
      # 配置主键自增
      id-type: auto